name: CI
on:
  pull_request: {}
  # push: {}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
        python-version: [2.7, 3.6, 3.7, 3.8, 3.9-dev]
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      # Install dependencies on ubuntu
      - if: matrix.os == 'ubuntu-latest'
        name: Install build dependencies
        run: sudo apt-get install -y libxml2-dev libxslt-dev golang-go


      # Install 32-bit windows target for pypy3
      - if: matrix.os == 'windows-latest' && matrix.python-version == 'pypy3'
        name: Install 32-bit Rust target
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: i686-pc-windows-msvc

      - name: Install setuptools-rust
        run: pip install setuptools-rust==0.10.3 wheel pytest pytest-benchmark

      - if: matrix.python-version == '2.7'
        name: Install benchmark dependencies for Python 2
        run: cd bench && pip install -r requirements2.txt

      - if: matrix.python-version != '2.7' && matrix.python-version != '3.9-dev'
        name: Install benchmark dependencies for Python 3
        run: cd bench && pip install -r requirements3.txt

      - name: Install library
        run: python setup.py install
        
      - if: matrix.python-version != '3.9-dev'
        name: Run benchmarks
        shell: bash
        run: |
          cd bench && pytest
        
      - name: Run tests
        if: ${{ !(matrix.os == 'windows-latest' && (matrix.python-version == 'pypy3' || matrix.python-version == '3.9-dev')) }}
        shell: bash
        run: |
          cd tests && pytest
  
