# @file package-release.yml
---
name: Python package release
on:
  release:
    types: [created]
jobs:
  release:
    # specify the instance
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [2.7, 3.6, 3.7, 3.8, 3.9-dev]
    steps:
    # checkout the repository to master
    # and use it as the current working directory
    - uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools-rust==0.10.3 wheel twine
        pip install twine flake8 
    - name: Build Python package
      run: |
        python setup.py sdist bdist_wheel
    - name: Twine check
      run: |
        twine check dist/*
    - name: Publish artifacts
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/*.whl
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
    #- name: Rename packages
    #  run: |
    #    cd dist/  
    #    rename  's/linux/manylinux2014/' *
    #    cd ..
    #- name: Publish to PyPI
    #  run: |
    #    twine upload --repository-url https://upload.pypi.org/legacy/ dist/* -u ${{ secrets.PYPI_USER }} -p ${{ secrets.PYPI_PASSWORD }}
